### ISSUE TITLE
KPI Services R Client Error

### ISSUE THREAD

**Issue by slamspitfolksong** [adjust/api-client-r#10]
#### Issue

A Client got the below error when using R client for our KPI services :

```
Error in if (resp$headers$`content-type` != "text/csv") { : 
  argument is of length zero
In addition: Warning message:
In strsplit(rawToChar(raw), "\r?\n") :
  input string 1 is invalid in this locale
```

Here’s the code they used:

![35afea58-49ab-11e6-9d7d-acd006fdd283](https://cloud.githubusercontent.com/assets/2988878/16852354/9f249892-49bc-11e6-9f45-a837f527d758.png)

They tried to update the R client using: `devtools::install_github('adjust/api-client-r');`
and got the following:

![ad9fd6bb435cda2de41fc3345469be70](https://cloud.githubusercontent.com/assets/16023673/16804879/13d03e12-490e-11e6-820b-54db02977220.png)

![5ee3d7b5a25a4aa8a99a42a9ed94372f](https://cloud.githubusercontent.com/assets/16023673/16832503/cd3c6c76-49aa-11e6-8f01-2711eb875251.png)

But the issue still persists when they run:

![f706c308-49aa-11e6-8f0f-2cec137aabd8](https://cloud.githubusercontent.com/assets/2988878/16852454/12b6219a-49bd-11e6-8809-a56cf5e6ab4a.png)

```
Error in if (resp$headers$`content-type` != "text/csv") { : 
  argument is of length zero
In addition: Warning message:
In strsplit(rawToChar(raw), "\r?\n") :
  input string 1 is invalid in this locale
```
#### Other Info:

R client version: 3.3.0
adjust package version: 0.0.5

**Comment by chochkov** [comment]
The issue was with the `httr` library processing response headers in Chinese locale. The workaround was to set the locale to english - for Windows using `Sys.setlocale("LC_ALL","English")`
