### ISSUE TITLE
Cohorts revenue_total grouping issue

### ISSUE THREAD

**Issue by jamiemlee** [adjust/api-client-r#17]
When extracting the revenue_total (cumulative revenue), if you set the period to day and the grouping by month it seems to default the period to month instead of day.

**Comment by chochkov** [comment]
@jamiemlee the way the API currently supports the behaviour you're looking for, is by doing multiple requests - each for each month you're interested in. Then for each request you don't need to group by month additionally and you can have the period-after-install being days.

Currently, the `group` parameter takes precedence over `period` and the period in the response gets fixed. 

Hope that helps.

**Comment by jamiemlee** [comment]
Ok thanks, that clarifies it!
