### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by mzaret2000** [adjust/api-client-r#8]
I'm having a problem connecting from R. The user token and app token seems to be valid as I can enter the url into chrome and get the expected response. I have successfully connected from R in the past.

```
adjust.setup(user.token='[redacted', app.token = 'redacted')
adjust.cohorts(countries=c('us', 'de'))
```

Request URL:
https://api.adjust.com/kpis/v1/redacted/cohorts.csv?countries=us,de

Error: `col_names` must be TRUE, FALSE or a character vector

**Comment by chochkov** [comment]
@mzaret2000 this issue is solved in the most recent version of the client. Simply update the package version from `R` by doing: `library(devtools); devtools::install_github('adjust/api-client-r');` and try again.

Please let us know if you're having further problems with this.

**Comment by mzaret2000** [comment]
Thank you @chochkov. That fixed the issue. We also access the api using the Requests library in Python and we recently started getting this exception:

ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer')) 

Do you have any recommendations for dealing with that?

**Comment by slamspitfolksong** [comment]
@mzaret2000 The error results from python2 not supporting SNI extensions to TLS fully. In python3 the error disappears. 

Seems others have encountered this as well: https://mail.python.org/pipermail/python-list/2014-October/678938.html

> I believe the problem is that the connection is protected by a multi-hostname server certificate and Python 2's `urllib` (and underlying `httplib` and ssl modules) do not support SNI extensions to TLS.  The request above works fine with Python 3 (which has supported client-side SNI since Python 3.2). See http://bugs.python.org/issue5639 for more discussion of the matter. If Python 3 is not an option for you, the requests package available via PyPI should help.
